/** @type {import('next').NextConfig} */
const nextConfig = {
  trailingSlash: true,
  typescript: {
    ignoreBuildErrors: true,
  },
  images: {
    unoptimized: true,
  },
  async redirects() {
    // Fêtes/saisons pages wrongly crawled under /mots-meles-thematiques/ → canonical silo
    const seasonalThemeRedirects = [
      "noel",
      "halloween",
      "paques",
      "carnaval",
      "rentree",
      "ete",
      "printemps",
    ].flatMap((slug) => [
      {
        source: `/mots-meles-thematiques/${slug}`,
        destination: `/mots-meles-fetes-saisons/${slug}/`,
        permanent: true,
      },
      {
        source: `/mots-meles-thematiques/${slug}/`,
        destination: `/mots-meles-fetes-saisons/${slug}/`,
        permanent: true,
      },
    ])

    // GSC soft-404s: legacy crawls invented path-style "/-N" pagination.
    // Live pagination uses ?page=N only — these are not generated by the app.
    // Specific destinations first (puzzle/app URLs map to silo hubs, not parent).
    const malformedPaginationRedirects = [
      {
        source: "/contact/-1",
        destination: "/contact/",
        permanent: true,
      },
      {
        source: "/contact/-1/",
        destination: "/contact/",
        permanent: true,
      },
      {
        source: "/mots-meles-fetes-saisons/-1",
        destination: "/mots-meles-fetes-saisons/",
        permanent: true,
      },
      {
        source: "/mots-meles-fetes-saisons/-1/",
        destination: "/mots-meles-fetes-saisons/",
        permanent: true,
      },
      {
        source: "/mots-meles/cp-vocabulaire-bonus-02/-3",
        destination: "/mots-meles-ecole/cp/",
        permanent: true,
      },
      {
        source: "/mots-meles/cp-vocabulaire-bonus-02/-3/",
        destination: "/mots-meles-ecole/cp/",
        permanent: true,
      },
      {
        source: "/mots-meles/animaux-facile-01/-3",
        destination: "/mots-meles-thematiques/animaux/",
        permanent: true,
      },
      {
        source: "/mots-meles/animaux-facile-01/-3/",
        destination: "/mots-meles-thematiques/animaux/",
        permanent: true,
      },
      {
        source: "/mots-meles/fruits-facile-04/-3",
        destination: "/mots-meles-thematiques/fruits/",
        permanent: true,
      },
      {
        source: "/mots-meles/fruits-facile-04/-3/",
        destination: "/mots-meles-thematiques/fruits/",
        permanent: true,
      },
      {
        source: "/mots-meles-thematiques/fruits/-2",
        destination: "/mots-meles-thematiques/fruits/",
        permanent: true,
      },
      {
        source: "/mots-meles-thematiques/fruits/-2/",
        destination: "/mots-meles-thematiques/fruits/",
        permanent: true,
      },
      {
        source: "/mots-meles-thematiques/meteo/-2",
        destination: "/mots-meles-thematiques/meteo/",
        permanent: true,
      },
      {
        source: "/mots-meles-thematiques/meteo/-2/",
        destination: "/mots-meles-thematiques/meteo/",
        permanent: true,
      },
      {
        source: "/application-mots-meles/-1",
        destination: "/app/",
        permanent: true,
      },
      {
        source: "/application-mots-meles/-1/",
        destination: "/app/",
        permanent: true,
      },
      // Catch-all: any other "/-N" trailing segment → parent path (301).
      {
        source: "/:path*/:page(-\\d+)",
        destination: "/:path*/",
        permanent: true,
      },
      {
        source: "/:path*/:page(-\\d+)/",
        destination: "/:path*/",
        permanent: true,
      },
    ]

    return [...seasonalThemeRedirects, ...malformedPaginationRedirects]
  },
  async rewrites() {
    return [
      // Serve the static Mots Mêlés PWA (public/app) at /app/
      { source: "/app", destination: "/app/index.html" },
      { source: "/app/", destination: "/app/index.html" },
    ]
  },
  async headers() {
    return [
      {
        source: "/.well-known/assetlinks.json",
        headers: [
          { key: "Content-Type", value: "application/json" },
          { key: "Cache-Control", value: "public, max-age=3600" },
        ],
      },
    ]
  },
}

export default nextConfig
