/** Reference difficulty levels — PRD Section 25.2 */
export const difficultySeed = [
  {
    slug: "facile",
    name: "Facile",
    gridSizeMin: 8,
    gridSizeMax: 8,
    wordCountMin: 6,
    wordCountMax: 8,
    directions: ["HORIZONTAL", "VERTICAL"],
  },
  {
    slug: "moyen",
    name: "Moyen",
    gridSizeMin: 10,
    gridSizeMax: 10,
    wordCountMin: 8,
    wordCountMax: 10,
    directions: [
      "HORIZONTAL",
      "VERTICAL",
      "DIAGONAL_DESCENDANTE",
      "DIAGONAL_MONTANTE",
    ],
  },
  {
    slug: "difficile",
    name: "Difficile",
    gridSizeMin: 12,
    gridSizeMax: 15,
    wordCountMin: 12,
    wordCountMax: 15,
    directions: [
      "HORIZONTAL",
      "HORIZONTAL_INVERSE",
      "VERTICAL",
      "VERTICAL_INVERSE",
      "DIAGONAL_DESCENDANTE",
      "DIAGONAL_DESCENDANTE_INVERSE",
      "DIAGONAL_MONTANTE",
      "DIAGONAL_MONTANTE_INVERSE",
    ],
  },
  {
    slug: "geant",
    name: "Géant",
    gridSizeMin: 18,
    gridSizeMax: 20,
    wordCountMin: 18,
    wordCountMax: 25,
    directions: [
      "HORIZONTAL",
      "HORIZONTAL_INVERSE",
      "VERTICAL",
      "VERTICAL_INVERSE",
      "DIAGONAL_DESCENDANTE",
      "DIAGONAL_DESCENDANTE_INVERSE",
      "DIAGONAL_MONTANTE",
      "DIAGONAL_MONTANTE_INVERSE",
    ],
  },
] as const
