/** MVP starter themes — PRD Section 6 (15 priority themes) */
export const themeSeed = [
  {
    slug: "noel",
    name: "Noël",
    group: "Saisons & Fêtes",
    isSeasonal: true,
    activeDateStart: "11-15",
    activeDateEnd: "01-06",
  },
  {
    slug: "halloween",
    name: "Halloween",
    group: "Saisons & Fêtes",
    isSeasonal: true,
    activeDateStart: "10-01",
    activeDateEnd: "10-31",
  },
  {
    slug: "paques",
    name: "Pâques",
    group: "Saisons & Fêtes",
    isSeasonal: true,
    activeDateStart: "03-15",
    activeDateEnd: "04-30",
  },
  {
    slug: "carnaval",
    name: "Carnaval",
    group: "Saisons & Fêtes",
    isSeasonal: true,
    activeDateStart: "01-20",
    activeDateEnd: "03-10",
  },
  {
    slug: "rentree",
    name: "Rentrée",
    group: "Saisons & Fêtes",
    isSeasonal: true,
    activeDateStart: "08-20",
    activeDateEnd: "09-30",
  },
  {
    slug: "ete",
    name: "Été",
    group: "Saisons & Fêtes",
    isSeasonal: true,
    activeDateStart: "06-01",
    activeDateEnd: "08-31",
  },
  {
    slug: "printemps",
    name: "Printemps",
    group: "Saisons & Fêtes",
    isSeasonal: true,
    activeDateStart: "03-01",
    activeDateEnd: "05-31",
  },
  {
    slug: "animaux",
    name: "Animaux",
    group: "Nature & Animaux",
    isSeasonal: false,
    activeDateStart: null,
    activeDateEnd: null,
  },
  {
    slug: "fruits",
    name: "Fruits",
    group: "Nature & Animaux",
    isSeasonal: false,
    activeDateStart: null,
    activeDateEnd: null,
  },
  {
    slug: "sport",
    name: "Sport",
    group: "Sport & Loisirs",
    isSeasonal: false,
    activeDateStart: null,
    activeDateEnd: null,
  },
  {
    slug: "football",
    name: "Football",
    group: "Sport & Loisirs",
    isSeasonal: false,
    activeDateStart: null,
    activeDateEnd: null,
  },
  {
    slug: "vocabulaire",
    name: "Vocabulaire",
    group: "École & Savoir",
    isSeasonal: false,
    activeDateStart: null,
    activeDateEnd: null,
  },
  {
    slug: "couleurs",
    name: "Couleurs",
    group: "École & Savoir",
    isSeasonal: false,
    activeDateStart: null,
    activeDateEnd: null,
  },
  {
    slug: "famille",
    name: "Famille",
    group: "Famille & Quotidien",
    isSeasonal: false,
    activeDateStart: null,
    activeDateEnd: null,
  },
  {
    slug: "meteo",
    name: "Météo",
    group: "Famille & Quotidien",
    isSeasonal: false,
    activeDateStart: null,
    activeDateEnd: null,
  },
  {
    slug: "corps-humain",
    name: "Corps humain",
    group: "Famille & Quotidien",
    isSeasonal: false,
    activeDateStart: null,
    activeDateEnd: null,
  },
  {
    slug: "pays-du-monde",
    name: "Pays du Monde",
    group: "Monde & Voyage",
    isSeasonal: false,
    activeDateStart: null,
    activeDateEnd: null,
  },
  {
    slug: "sciences",
    name: "Sciences",
    group: "École & Savoir",
    isSeasonal: false,
    activeDateStart: null,
    activeDateEnd: null,
  },
  {
    slug: "metiers",
    name: "Métiers",
    group: "École & Savoir",
    isSeasonal: false,
    activeDateStart: null,
    activeDateEnd: null,
  },
] as const

export type ThemeSlug = (typeof themeSeed)[number]["slug"]
